### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by hugolpz** [CyberCRI/PiratePartageMobile#1]
- [x] Add introductory line.
- [x] Complete minimalist readme.md

Note : Consider the existance of both 
- https://github.com/CyberCRI/PiratePartage
- https://github.com/CyberCRI/PiratePartageMobile

**Comment by drpepper** [comment]
Will do soon...

**Comment by hugolpz** [comment]
Pirates !
------------
**Pirates** is an educational game with which players take over the life of battle hardened Pirates with handicaps. Between battles against the Royal Navy, these tenacious seniors pirates love to trade with each other, which is both lot of tough and fun as each is differently handicapped yet love trading. You must trade and collaborate as much as possible to satisfy your sailors, have them ready and willing for defenses against the navy's teases, and cooperate in your defense despites your various punctual shortcomings.

**Comment :** The game put the players in the tricky situation of having a real handicap, yet having to collaborate intensively. Along the party, players develop personal and collaborative strategies enlightening how, despite handicaps, people can be efficient and full scale social actors based on special efforts, awareness, social inclusion and collaboration.

## Repository
### Technical side
**Problematic:** this repository support the game<br>
**Version:** v.0.x.x.<br>
**Stack:** [...]

### Code structure
```
 + README.md  -- human friendly introduction
 +-- Assets -- various materials to create the card game
 +-- Cards	-- cards generator
 +-- ProjectSettings	-- technical side
```

## Game


#### Vocabulary
* **[something]** : [clarification]

#### Requirements
Material :
* Complete play deck with [n] cards
* Decoy for diamonds [n], wine bottles [n], parchment [n], canon's balls [n]
Players : 4+
Age : 7 to 77+

### Rules
**Roles assignments :** 
There are 4 roles : blind, mute, deft, handless. For each role, the players throw the dice. The player with the lowest number with the handicap ! Repeat until each player has an handicap. Each player has to "implement the handicap" :
* The Mute cannot speak : he wears a mount mask !
* The Blind cannot see : you wear an eyes mask.
* The Deft cannot hear : you wear earplugs with some rocky musics ! 
* The Handless cannot grab : you use a prosthesis, chopsticks or cooking gloves !

**Cards distributions:** Sort the cards by numbers. Follow the app to distribute the cards.

### Playing
**Announcement :**
>Dear Captains, dear Pirates !
>Each of you has and leads one pirate ship with [x] diamonds, [x] wine bottles, [x] parchemin, [x] canon's balls to trade around.
>Each of you has one handicap. 
>The Mute, you cannot speak. The Blind, you cannot see.
>The Deft you cannot hear. The Handless, you cannot grab... and must use prostheses (chopsticks)
>You got cards telling you what to trade with who, in order to make your whole marine happy and ready for battle.
>You can use your abilities to communicate with your target... or ask for help.
>Remember to watch out !! The Royal Navy is around and sneaky!! She can attack anytime, to which you must join force on the app.
>Your objective is collaborative : at the end of a cycle, you must have successfully trade as much cards as possible !
>Good luck, rich live the Pirates !

### Navy attack
<explain>

### License
CC-BY-SA-NC-4.0 -- Jesse, Center for Research in Interdisciplinarity (@CRIparis)
